# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      HOST: demo-de.leanix.net
      LEANIX_MANIFEST_PATH: /manifest.yml
      DEPENDENCY_MANAGER: NPM
      LEANIX_API_TOKEN: 3SXTecJaxSb5sfyWHAAKdxH6fteOnXgn4RzgkBUD
      STAGE: production
      VERSION: 1.0.0
      ALLOW_FAILURE: true


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: LeanIX Value Stream Management action
      uses: leanix/github-actions-store-leanix-plugin@1.2.6
      id: LIXVSM
      with:  
        host: ${{ env.HOST }}  
        api-token: ${{ env.LEANIX_API_TOKEN }}  
        manifest-path: ${{ env.LEANIX_MANIFEST_PATH }}  
        dependency-manager: ${{ env.DEPENDENCY_MANAGER }}  
        stage: ${{ env.STAGE }}  
        version: ${{ env.VERSION }}
        allow-failure: ${{ env.ALLOW_FAILURE }}
